- name: Invoke workflow without inputs. Wait for result
  uses: aurelien-baudet/workflow-dispatch@v2
  with:
    workflow: Events Demo 1
    token: ${{ secrets.PERSONAL_TOKEN }}
    
- name: Invoke workflow without inputs. Don't wait for result
  uses: aurelien-baudet/workflow-dispatch@v2
  with:
    workflow: Events Demo
    token: ${{ secrets.PERSONAL_TOKEN }}
    wait-for-completion: false
